import type {
  Patient,
  Doctor,
  Appointment,
  Treatment,
  Invoice,
  TestCatalogItem,
  AuditLogEntry,
  User,
} from "./types"

// ============================================================
// Users (for role switcher)
// ============================================================
export const MOCK_USERS: User[] = [
  { id: "u1", name: "Dr. Admin", role: "admin", email: "admin@clinic.com" },
  { id: "u2", name: "Dr. Sarah Chen", role: "doctor", email: "sarah@clinic.com" },
  { id: "u3", name: "James Wilson", role: "manager", email: "james@clinic.com" },
  { id: "u4", name: "Emily Davis", role: "accounts", email: "emily@clinic.com" },
]

// ============================================================
// Doctors
// ============================================================
export const MOCK_DOCTORS: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Sarah Chen",
    specialty: "General Medicine",
    phone: "+92 300 1230001",
    email: "sarah@clinic.com",
    consultationFee: 150,
    schedule: [
      { day: "Monday", startTime: "09:00", endTime: "17:00" },
      { day: "Tuesday", startTime: "09:00", endTime: "17:00" },
      { day: "Wednesday", startTime: "09:00", endTime: "13:00" },
      { day: "Thursday", startTime: "09:00", endTime: "17:00" },
      { day: "Friday", startTime: "09:00", endTime: "17:00" },
    ],
    isActive: true,
  },
  {
    id: "d2",
    name: "Dr. Michael Park",
    specialty: "Cardiology",
    phone: "+92 321 1230002",
    email: "michael@clinic.com",
    consultationFee: 200,
    schedule: [
      { day: "Monday", startTime: "10:00", endTime: "18:00" },
      { day: "Wednesday", startTime: "10:00", endTime: "18:00" },
      { day: "Friday", startTime: "10:00", endTime: "16:00" },
    ],
    isActive: true,
  },
  {
    id: "d3",
    name: "Dr. Lisa Patel",
    specialty: "Dermatology",
    phone: "+92 333 1230003",
    email: "lisa@clinic.com",
    consultationFee: 175,
    schedule: [
      { day: "Tuesday", startTime: "09:00", endTime: "17:00" },
      { day: "Thursday", startTime: "09:00", endTime: "17:00" },
      { day: "Saturday", startTime: "09:00", endTime: "13:00" },
    ],
    isActive: true,
  },
  {
    id: "d4",
    name: "Dr. James Rodriguez",
    specialty: "Orthopedics",
    phone: "+92 311 1230004",
    email: "james.r@clinic.com",
    consultationFee: 225,
    schedule: [
      { day: "Monday", startTime: "08:00", endTime: "16:00" },
      { day: "Wednesday", startTime: "08:00", endTime: "16:00" },
      { day: "Thursday", startTime: "08:00", endTime: "16:00" },
    ],
    isActive: true,
  },
]

// ============================================================
// Test Catalog
// ============================================================
export const MOCK_TEST_CATALOG: TestCatalogItem[] = [
  // ── Blood Tests ──────────────────────────────────────────
  { id: "t1",  name: "Complete Blood Count (CBC)",       category: "Blood Test",   price: 800,   urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "t2",  name: "Lipid Panel",                      category: "Blood Test",   price: 1500,  urgencyOptions: ["routine"], isActive: true },
  { id: "t3",  name: "Blood Glucose (Fasting)",          category: "Blood Test",   price: 300,   urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "t10", name: "HbA1c",                            category: "Blood Test",   price: 1200,  urgencyOptions: ["routine"], isActive: true },
  // ── Biochemistry ─────────────────────────────────────────
  { id: "t4",  name: "Thyroid Panel (TSH, T3, T4)",      category: "Biochemistry", price: 2500,  urgencyOptions: ["routine"], isActive: true },
  { id: "t8",  name: "Liver Function Test (LFT)",        category: "Biochemistry", price: 2000,  urgencyOptions: ["routine"], isActive: true },
  { id: "t9",  name: "Kidney Function Test (KFT)",       category: "Biochemistry", price: 2000,  urgencyOptions: ["routine"], isActive: true },
  { id: "t11", name: "Vitamin D Level",                  category: "Biochemistry", price: 3000,  urgencyOptions: ["routine"], isActive: true },
  // ── Urine & Pathology ─────────────────────────────────────
  { id: "t5",  name: "Urinalysis (Complete)",            category: "Urine Test",   price: 400,   urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "t12", name: "Skin Biopsy",                      category: "Pathology",    price: 5000,  urgencyOptions: ["routine", "urgent"], isActive: true },
  // ── Cardiac & Imaging ─────────────────────────────────────
  { id: "t7",  name: "ECG / EKG",                        category: "Cardiac",      price: 800,   urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "t6",  name: "Chest X-Ray",                      category: "Imaging",      price: 1500,  urgencyOptions: ["routine", "urgent", "stat"], isActive: true },
  // ── Ultrasound ────────────────────────────────────────────
  { id: "u1",  name: "Ultrasound - Normal Abdomen",      category: "Ultrasound",   price: 2500,  urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "u2",  name: "Ultrasound - Obstetric (Obs)",     category: "Ultrasound",   price: 2500,  urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "u3",  name: "Ultrasound - Pelvic",              category: "Ultrasound",   price: 2500,  urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "u4",  name: "Ultrasound - Breast",              category: "Ultrasound",   price: 4000,  urgencyOptions: ["routine"], isActive: true },
  { id: "u5",  name: "Ultrasound - Thyroid",             category: "Ultrasound",   price: 4000,  urgencyOptions: ["routine"], isActive: true },
  { id: "u6",  name: "Ultrasound - MSK",                 category: "Ultrasound",   price: 4000,  urgencyOptions: ["routine"], isActive: true },
  { id: "u7",  name: "TVS (Transvaginal Scan)",          category: "Ultrasound",   price: 3500,  urgencyOptions: ["routine", "urgent"], isActive: true },
  // ── Doppler Studies ───────────────────────────────────────
  { id: "d1",  name: "Doppler - Obstetric",              category: "Doppler",      price: 3500,  urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "d2",  name: "Doppler - Abdomen",                category: "Doppler",      price: 3500,  urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "d3",  name: "Doppler - Neck / Carotid",         category: "Doppler",      price: 4000,  urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "d4",  name: "Doppler - Carotid (Full)",         category: "Doppler",      price: 6000,  urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "d5",  name: "Doppler - Legs (Per Leg)",         category: "Doppler",      price: 3500,  urgencyOptions: ["routine", "urgent"], isActive: true },
  { id: "d6",  name: "Doppler - Both Legs",              category: "Doppler",      price: 7000,  urgencyOptions: ["routine", "urgent"], isActive: true },
]

// ============================================================
// Patients
// ============================================================
export const MOCK_PATIENTS: Patient[] = [
  {
    id: "p1",
    name: "Alice Johnson",
    phone: "0300-1234001",
    email: "alice.j@email.com",
    gender: "female",
    age: 34,
    dateOfBirth: "1991-06-15",
    address: "456 Oak Street, Apt 2B",
    bloodGroup: "A+",
    tags: ["diabetes", "regular"],
    notes: "Allergic to penicillin. Requires insulin management.",
    assignedDoctorId: "d1",
    medicalHistory: [
      { id: "mh1", date: "2025-01-15", type: "Diagnosis", description: "Type 2 Diabetes diagnosed. Started metformin 500mg.", addedBy: "Dr. Sarah Chen" },
      { id: "mh2", date: "2025-06-20", type: "Lab Result", description: "HbA1c: 7.2% - slightly above target.", addedBy: "Dr. Sarah Chen" },
    ],
    documents: [
      { id: "doc1", name: "Initial Assessment Report.pdf", type: "PDF", uploadedAt: "2025-01-15", uploadedBy: "Dr. Sarah Chen", url: "#" },
    ],
    createdAt: "2025-01-10",
    updatedAt: "2026-02-15",
  },
  {
    id: "p2",
    name: "Robert Smith",
    phone: "0321-1234002",
    email: "robert.s@email.com",
    gender: "male",
    age: 58,
    dateOfBirth: "1967-11-28",
    address: "789 Elm Avenue",
    bloodGroup: "O+",
    tags: ["cardiac", "hypertension"],
    notes: "History of hypertension. On beta-blockers.",
    assignedDoctorId: "d2",
    medicalHistory: [
      { id: "mh3", date: "2024-08-10", type: "Diagnosis", description: "Hypertension Stage 2. Started atenolol 50mg.", addedBy: "Dr. Michael Park" },
      { id: "mh4", date: "2025-12-01", type: "Follow-up", description: "BP stable at 130/85. Continue current medication.", addedBy: "Dr. Michael Park" },
    ],
    documents: [],
    createdAt: "2024-08-05",
    updatedAt: "2026-02-10",
  },
  {
    id: "p3",
    name: "Maria Garcia",
    phone: "0333-1234003",
    email: "maria.g@email.com",
    gender: "female",
    age: 27,
    dateOfBirth: "1998-03-22",
    address: "321 Pine Road, Unit 5",
    bloodGroup: "B+",
    tags: ["dermatology"],
    notes: "Sensitive skin. History of eczema.",
    assignedDoctorId: "d3",
    medicalHistory: [
      { id: "mh5", date: "2025-09-15", type: "Diagnosis", description: "Atopic dermatitis - moderate severity.", addedBy: "Dr. Lisa Patel" },
    ],
    documents: [],
    createdAt: "2025-09-10",
    updatedAt: "2026-01-20",
  },
  {
    id: "p4",
    name: "David Lee",
    phone: "0311-1234004",
    gender: "male",
    age: 45,
    dateOfBirth: "1980-07-08",
    address: "567 Maple Drive",
    bloodGroup: "AB+",
    tags: ["orthopedic", "sports-injury"],
    notes: "Active runner. Previous ACL surgery (2019).",
    assignedDoctorId: "d4",
    medicalHistory: [
      { id: "mh6", date: "2025-11-05", type: "Procedure", description: "ACL reconstruction - right knee. Full recovery expected.", addedBy: "Dr. James Rodriguez" },
    ],
    documents: [
      { id: "doc2", name: "MRI Report - Right Knee.pdf", type: "PDF", uploadedAt: "2025-10-20", uploadedBy: "Dr. James Rodriguez", url: "#" },
    ],
    createdAt: "2025-10-15",
    updatedAt: "2026-02-01",
  },
  {
    id: "p5",
    name: "Sarah Williams",
    phone: "0345-1234005",
    email: "sarah.w@email.com",
    gender: "female",
    age: 42,
    dateOfBirth: "1983-12-03",
    bloodGroup: "A-",
    tags: ["regular", "thyroid"],
    notes: "Hypothyroidism. Annual check-ups.",
    assignedDoctorId: "d1",
    medicalHistory: [],
    documents: [],
    createdAt: "2024-03-20",
    updatedAt: "2026-01-28",
  },
  {
    id: "p6",
    name: "James Brown",
    phone: "0301-1234006",
    gender: "male",
    age: 65,
    dateOfBirth: "1960-09-17",
    address: "890 Cedar Lane",
    bloodGroup: "O-",
    tags: ["cardiac", "diabetes", "senior"],
    notes: "Multiple comorbidities. Requires careful medication management.",
    assignedDoctorId: "d2",
    medicalHistory: [
      { id: "mh7", date: "2025-05-10", type: "Diagnosis", description: "Atrial fibrillation detected. Started anticoagulation therapy.", addedBy: "Dr. Michael Park" },
    ],
    documents: [],
    createdAt: "2024-01-15",
    updatedAt: "2026-02-18",
  },
  {
    id: "p7",
    name: "Emma Wilson",
    phone: "0322-1234007",
    email: "emma.w@email.com",
    gender: "female",
    age: 31,
    dateOfBirth: "1994-04-25",
    bloodGroup: "B-",
    tags: ["dermatology", "cosmetic"],
    notes: "Acne treatment plan in progress.",
    assignedDoctorId: "d3",
    medicalHistory: [],
    documents: [],
    createdAt: "2025-11-01",
    updatedAt: "2026-02-12",
  },
  {
    id: "p8",
    name: "Thomas Anderson",
    phone: "0312-1234008",
    gender: "male",
    age: 52,
    dateOfBirth: "1973-08-14",
    address: "234 Birch Street",
    bloodGroup: "AB-",
    tags: ["orthopedic"],
    notes: "Chronic lower back pain. Physical therapy recommended.",
    assignedDoctorId: "d4",
    medicalHistory: [],
    documents: [],
    createdAt: "2025-07-20",
    updatedAt: "2026-01-15",
  },
]

// ============================================================
// Appointments (today: 2026-02-20, recent past, and upcoming)
// ============================================================
export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "a1",
    patientId: "p1",
    doctorId: "d1",
    date: "2026-02-20",
    time: "09:00",
    duration: 30,
    status: "scheduled",
    type: "Follow-up",
    notes: "Diabetes follow-up. Check HbA1c results.",
    receptionNotes: "Patient confirmed via phone.",
    doctorNotes: "",
    invoiceId: "inv1",
    createdAt: "2026-02-15",
    updatedAt: "2026-02-15",
  },
  {
    id: "a2",
    patientId: "p2",
    doctorId: "d2",
    date: "2026-02-20",
    time: "10:00",
    duration: 45,
    status: "checked-in",
    type: "Consultation",
    notes: "Cardiac check-up. ECG scheduled.",
    receptionNotes: "Patient arrived early.",
    doctorNotes: "",
    invoiceId: "inv2",
    createdAt: "2026-02-14",
    updatedAt: "2026-02-20",
  },
  {
    id: "a3",
    patientId: "p3",
    doctorId: "d3",
    date: "2026-02-20",
    time: "11:00",
    duration: 30,
    status: "scheduled",
    type: "Follow-up",
    notes: "Dermatitis check. Review cream effectiveness.",
    receptionNotes: "",
    doctorNotes: "",
    invoiceId: "inv3",
    createdAt: "2026-02-16",
    updatedAt: "2026-02-16",
  },
  {
    id: "a4",
    patientId: "p4",
    doctorId: "d4",
    date: "2026-02-20",
    time: "14:00",
    duration: 60,
    status: "scheduled",
    type: "Post-Surgery",
    notes: "Post-ACL surgery follow-up at 3 months.",
    receptionNotes: "",
    doctorNotes: "",
    invoiceId: "inv4",
    createdAt: "2026-02-10",
    updatedAt: "2026-02-10",
  },
  {
    id: "a5",
    patientId: "p5",
    doctorId: "d1",
    date: "2026-02-20",
    time: "15:30",
    duration: 30,
    status: "scheduled",
    type: "Annual Check-up",
    notes: "Annual thyroid panel + general health.",
    receptionNotes: "",
    doctorNotes: "",
    invoiceId: "inv5",
    createdAt: "2026-02-12",
    updatedAt: "2026-02-12",
  },
  {
    id: "a6",
    patientId: "p6",
    doctorId: "d2",
    date: "2026-02-21",
    time: "10:00",
    duration: 45,
    status: "scheduled",
    type: "Follow-up",
    notes: "AF management review. Check INR levels.",
    receptionNotes: "",
    doctorNotes: "",
    invoiceId: "inv6",
    createdAt: "2026-02-18",
    updatedAt: "2026-02-18",
  },
  {
    id: "a7",
    patientId: "p7",
    doctorId: "d3",
    date: "2026-02-22",
    time: "09:00",
    duration: 30,
    status: "scheduled",
    type: "Treatment",
    notes: "Acne treatment session 3 of 6.",
    receptionNotes: "",
    doctorNotes: "",
    invoiceId: "inv7",
    createdAt: "2026-02-17",
    updatedAt: "2026-02-17",
  },
  // Past appointments
  {
    id: "a8",
    patientId: "p1",
    doctorId: "d1",
    date: "2026-02-13",
    time: "09:30",
    duration: 30,
    status: "completed",
    type: "Consultation",
    notes: "Initial consultation for medication review.",
    receptionNotes: "Patient on time.",
    doctorNotes: "Adjusted metformin to 1000mg. Ordered HbA1c.",
    invoiceId: "inv8",
    createdAt: "2026-02-08",
    updatedAt: "2026-02-13",
  },
  {
    id: "a9",
    patientId: "p2",
    doctorId: "d2",
    date: "2026-02-10",
    time: "11:00",
    duration: 45,
    status: "completed",
    type: "ECG Review",
    notes: "Routine cardiac monitoring.",
    receptionNotes: "",
    doctorNotes: "ECG normal sinus rhythm. BP 128/82. Continue current meds.",
    invoiceId: "inv9",
    createdAt: "2026-02-05",
    updatedAt: "2026-02-10",
  },
  {
    id: "a10",
    patientId: "p8",
    doctorId: "d4",
    date: "2026-02-18",
    time: "08:30",
    duration: 30,
    status: "cancelled",
    type: "Follow-up",
    notes: "Back pain follow-up.",
    receptionNotes: "Patient called to cancel - rescheduling.",
    doctorNotes: "",
    invoiceId: "inv10",
    createdAt: "2026-02-12",
    updatedAt: "2026-02-17",
  },
]

// ============================================================
// Invoices
// ============================================================
export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv1",
    patientId: "p1",
    appointmentId: "a1",
    doctorId: "d1",
    lineItems: [
      { id: "li1", description: "Consultation - Dr. Sarah Chen", category: "consultation", amount: 150, quantity: 1 },
      { id: "li2", description: "HbA1c Test", category: "test", amount: 40, quantity: 1 },
    ],
    totalAmount: 190,
    paidAmount: 0,
    balance: 190,
    status: "unpaid",
    payments: [],
    createdAt: "2026-02-15",
    updatedAt: "2026-02-15",
  },
  {
    id: "inv2",
    patientId: "p2",
    appointmentId: "a2",
    doctorId: "d2",
    lineItems: [
      { id: "li3", description: "Consultation - Dr. Michael Park", category: "consultation", amount: 200, quantity: 1 },
      { id: "li4", description: "ECG / EKG", category: "test", amount: 80, quantity: 1 },
    ],
    totalAmount: 280,
    paidAmount: 100,
    balance: 180,
    status: "partially-paid",
    payments: [
      { id: "pay1", invoiceId: "inv2", amount: 100, method: "card", reference: "TXN-20260218-001", notes: "Partial payment at check-in", collectedBy: "Emily Davis", collectedAt: "2026-02-20T10:05:00" },
    ],
    createdAt: "2026-02-14",
    updatedAt: "2026-02-20",
  },
  {
    id: "inv3",
    patientId: "p3",
    appointmentId: "a3",
    doctorId: "d3",
    lineItems: [
      { id: "li5", description: "Consultation - Dr. Lisa Patel", category: "consultation", amount: 175, quantity: 1 },
    ],
    totalAmount: 175,
    paidAmount: 0,
    balance: 175,
    status: "unpaid",
    payments: [],
    createdAt: "2026-02-16",
    updatedAt: "2026-02-16",
  },
  {
    id: "inv4",
    patientId: "p4",
    appointmentId: "a4",
    doctorId: "d4",
    lineItems: [
      { id: "li6", description: "Post-Surgery Review - Dr. James Rodriguez", category: "consultation", amount: 225, quantity: 1 },
      { id: "li7", description: "Chest X-Ray", category: "test", amount: 120, quantity: 1 },
    ],
    totalAmount: 345,
    paidAmount: 0,
    balance: 345,
    status: "unpaid",
    payments: [],
    createdAt: "2026-02-10",
    updatedAt: "2026-02-10",
  },
  {
    id: "inv5",
    patientId: "p5",
    appointmentId: "a5",
    doctorId: "d1",
    lineItems: [
      { id: "li8", description: "Annual Check-up - Dr. Sarah Chen", category: "consultation", amount: 150, quantity: 1 },
      { id: "li9", description: "Thyroid Panel (TSH, T3, T4)", category: "test", amount: 75, quantity: 1 },
      { id: "li10", description: "Complete Blood Count (CBC)", category: "test", amount: 35, quantity: 1 },
    ],
    totalAmount: 260,
    paidAmount: 260,
    balance: 0,
    status: "paid",
    payments: [
      { id: "pay2", invoiceId: "inv5", amount: 260, method: "cash", reference: "CASH-20260218", notes: "Full payment", collectedBy: "Emily Davis", collectedAt: "2026-02-18T15:45:00" },
    ],
    createdAt: "2026-02-12",
    updatedAt: "2026-02-18",
  },
  {
    id: "inv6",
    patientId: "p6",
    appointmentId: "a6",
    doctorId: "d2",
    lineItems: [
      { id: "li11", description: "Consultation - Dr. Michael Park", category: "consultation", amount: 200, quantity: 1 },
    ],
    totalAmount: 200,
    paidAmount: 0,
    balance: 200,
    status: "unpaid",
    payments: [],
    createdAt: "2026-02-18",
    updatedAt: "2026-02-18",
  },
  {
    id: "inv7",
    patientId: "p7",
    appointmentId: "a7",
    doctorId: "d3",
    lineItems: [
      { id: "li12", description: "Acne Treatment Session - Dr. Lisa Patel", category: "procedure", amount: 175, quantity: 1 },
    ],
    totalAmount: 175,
    paidAmount: 175,
    balance: 0,
    status: "paid",
    payments: [
      { id: "pay3", invoiceId: "inv7", amount: 175, method: "upi", reference: "UPI-20260219-003", notes: "Pre-paid for session", collectedBy: "James Wilson", collectedAt: "2026-02-19T09:15:00" },
    ],
    createdAt: "2026-02-17",
    updatedAt: "2026-02-19",
  },
  {
    id: "inv8",
    patientId: "p1",
    appointmentId: "a8",
    doctorId: "d1",
    lineItems: [
      { id: "li13", description: "Consultation - Dr. Sarah Chen", category: "consultation", amount: 150, quantity: 1 },
    ],
    totalAmount: 150,
    paidAmount: 150,
    balance: 0,
    status: "paid",
    payments: [
      { id: "pay4", invoiceId: "inv8", amount: 150, method: "cash", reference: "CASH-20260213", notes: "", collectedBy: "Emily Davis", collectedAt: "2026-02-13T09:40:00" },
    ],
    createdAt: "2026-02-08",
    updatedAt: "2026-02-13",
  },
  {
    id: "inv9",
    patientId: "p2",
    appointmentId: "a9",
    doctorId: "d2",
    lineItems: [
      { id: "li14", description: "ECG Review - Dr. Michael Park", category: "consultation", amount: 200, quantity: 1 },
      { id: "li15", description: "ECG / EKG", category: "test", amount: 80, quantity: 1 },
    ],
    totalAmount: 280,
    paidAmount: 280,
    balance: 0,
    status: "paid",
    payments: [
      { id: "pay5", invoiceId: "inv9", amount: 280, method: "bank-transfer", reference: "BT-20260210-001", notes: "", collectedBy: "Emily Davis", collectedAt: "2026-02-10T11:50:00" },
    ],
    createdAt: "2026-02-05",
    updatedAt: "2026-02-10",
  },
  {
    id: "inv10",
    patientId: "p8",
    appointmentId: "a10",
    doctorId: "d4",
    lineItems: [
      { id: "li16", description: "Follow-up - Dr. James Rodriguez", category: "consultation", amount: 225, quantity: 1 },
    ],
    totalAmount: 225,
    paidAmount: 0,
    balance: 225,
    status: "voided",
    payments: [],
    createdAt: "2026-02-12",
    updatedAt: "2026-02-17",
  },
]

// ============================================================
// Treatments
// ============================================================
export const MOCK_TREATMENTS: Treatment[] = [
  {
    id: "tr1",
    patientId: "p1",
    doctorId: "d1",
    appointmentId: "a8",
    date: "2026-02-13",
    complaint: "Feeling fatigued, increased thirst and urination.",
    clinicalNotes: "Patient reports increased fatigue over past 2 weeks. Blood sugar log shows fasting glucose averaging 160mg/dL.",
    diagnosis: "Uncontrolled Type 2 Diabetes",
    prescribedInstructions: "Increase Metformin to 1000mg twice daily. Strict dietary control. Walk 30 min daily.",
    testsRecommended: ["t10", "t1", "t9"],
    doctorSummary: "Adjusted diabetes management. Ordered HbA1c and kidney function tests.",
    followUpDate: "2026-02-20",
    attachments: [],
    status: "follow-up-needed",
    createdAt: "2026-02-13",
    updatedAt: "2026-02-13",
  },
  {
    id: "tr2",
    patientId: "p2",
    doctorId: "d2",
    appointmentId: "a9",
    date: "2026-02-10",
    complaint: "Occasional chest tightness during exercise.",
    clinicalNotes: "Patient reports mild chest tightness during jogging. No pain at rest. BP 128/82.",
    diagnosis: "Stable hypertension with exercise intolerance",
    prescribedInstructions: "Continue atenolol 50mg. Add amlodipine 5mg. Limit intense exercise temporarily.",
    testsRecommended: ["t7", "t2"],
    doctorSummary: "ECG shows normal sinus rhythm. Added calcium channel blocker for better BP control.",
    followUpDate: "2026-02-20",
    attachments: [],
    status: "follow-up-needed",
    createdAt: "2026-02-10",
    updatedAt: "2026-02-10",
  },
  {
    id: "tr3",
    patientId: "p3",
    doctorId: "d3",
    appointmentId: "a3",
    date: "2025-12-15",
    complaint: "Persistent dry, itchy patches on arms and neck.",
    clinicalNotes: "Moderate atopic dermatitis. Patches on bilateral forearms and posterior neck.",
    diagnosis: "Atopic Dermatitis - Moderate",
    prescribedInstructions: "Apply hydrocortisone 1% cream twice daily. Use fragrance-free moisturizer. Avoid hot showers.",
    testsRecommended: [],
    doctorSummary: "Started topical steroid regimen. Follow-up in 6 weeks to assess response.",
    followUpDate: "2026-02-20",
    attachments: [],
    status: "completed",
    createdAt: "2025-12-15",
    updatedAt: "2025-12-15",
  },
]

// ============================================================
// Audit Log
// ============================================================
export const MOCK_AUDIT_LOG: AuditLogEntry[] = [
  { id: "al1", userId: "u4", userName: "Emily Davis", userRole: "accounts", action: "Payment Collected", entity: "Invoice", entityId: "inv2", details: "Collected $100 via card for Invoice #inv2", timestamp: "2026-02-20T10:05:00" },
  { id: "al2", userId: "u3", userName: "James Wilson", userRole: "manager", action: "Appointment Created", entity: "Appointment", entityId: "a6", details: "Booked appointment for James Brown with Dr. Michael Park on Feb 21", timestamp: "2026-02-18T14:30:00" },
  { id: "al3", userId: "u2", userName: "Dr. Sarah Chen", userRole: "doctor", action: "Treatment Created", entity: "Treatment", entityId: "tr1", details: "Created treatment record for Alice Johnson - Diabetes management", timestamp: "2026-02-13T10:00:00" },
  { id: "al4", userId: "u1", userName: "Dr. Admin", userRole: "admin", action: "Patient Created", entity: "Patient", entityId: "p8", details: "Registered new patient: Thomas Anderson", timestamp: "2025-07-20T09:15:00" },
  { id: "al5", userId: "u4", userName: "Emily Davis", userRole: "accounts", action: "Payment Collected", entity: "Invoice", entityId: "inv5", details: "Collected $260 cash for Invoice #inv5 - Full payment", timestamp: "2026-02-18T15:45:00" },
  { id: "al6", userId: "u3", userName: "James Wilson", userRole: "manager", action: "Appointment Cancelled", entity: "Appointment", entityId: "a10", details: "Cancelled appointment for Thomas Anderson - patient request", timestamp: "2026-02-17T11:20:00" },
  { id: "al7", userId: "u1", userName: "Dr. Admin", userRole: "admin", action: "Invoice Voided", entity: "Invoice", entityId: "inv10", details: "Voided Invoice #inv10 due to appointment cancellation", timestamp: "2026-02-17T11:25:00" },
  { id: "al8", userId: "u2", userName: "Dr. Sarah Chen", userRole: "doctor", action: "Treatment Updated", entity: "Treatment", entityId: "tr2", details: "Updated treatment notes for Robert Smith", timestamp: "2026-02-10T12:00:00" },
  { id: "al9", userId: "u3", userName: "James Wilson", userRole: "manager", action: "Payment Collected", entity: "Invoice", entityId: "inv7", details: "Collected $175 via UPI for Invoice #inv7", timestamp: "2026-02-19T09:15:00" },
  { id: "al10", userId: "u1", userName: "Dr. Admin", userRole: "admin", action: "Test Added", entity: "Test Catalog", entityId: "t12", details: "Added Skin Biopsy to test catalog", timestamp: "2025-09-01T08:30:00" },
]
